[book]
authors = [
    "Alexandre Pigozzo",
    "Brenno Lemos",
    "Davi Jannotti Coelho Pinheiro",
    "Diego Augusto Silva Castro",
    "Sávio Francisco Cirino da Paz"
]
language = "en"
multilingual = false
src = "src"
title = "ODE Designer: Software Documentation"
