on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the AppImage
        shell: bash
        run: docker build -t ode-designer-appimage-builder --output=. .

      - name: Attach AppImage to Release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.event.release.tag_name }} ./ode-designer.AppImage
